### ISSUE TITLE
🤔 In review: patient search getter

### ISSUE THREAD

**Issue by rafael-parayno** [umed-jp/umed#2]
Issue are on the backend when it searches with a patient without a kana name 

to fix it needs to make it backwards compatibility

```
Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/app/src/utils/middleware.py", line 54, in wrapper
    return func(*args, **kwargs)
  File "/app/src/utils/middleware.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/app/src/blueprints/patients.py", line 39, in get_patients
    return PatientController().get_patients(request)
  File "/app/src/blueprints/patients.py", line 126, in get_patients
    patients = self.resource_client.search("Patient", search_clause)
  File "/app/src/adapters/fhir_store.py", line 205, in search
    return construct_fhir_element("Bundle", response.json())
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/fhir/resources/__init__.py", line 26, in construct_fhir_element
    return klass.parse_obj(data)
  File "pydantic/main.py", line 527, in pydantic.main.BaseModel.parse_obj
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/fhir/resources/fhirabstractmodel.py", line 138, in __init__
    BaseModel.__init__(__pydantic_self__, **data)
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Bundle
entry -> 3 -> resource -> name -> 0 -> family
  string does not match regex "[ \r\n\t\S]+" (type=value_error.str.regex; pattern=[ \r\n\t
  ```

**Comment by castilloglenn** [comment]
This one is critical for the list of patients (route `/patients`)  in the `practitioner-web-ts`.

**Comment by fauortiz** [comment]
**Investigation results:**

The bug is from a patient that registered in Sep 2022. Initially the hypothesis was that the patient did not have a kana name, which caused the error.

However, through consulting with @Grrom, when he fixed the error on the specific patient, that patient had an invalid whitespace character at the end of one of her names. Removing that fixed the error.

The FHIR module on the backend uses the regex "[ \r\n\t\S]+" to validate string data. This matches any string that contains one or more of only non-whitespace characters, spaces, carriage returns, newlines, or tabs.

However, it does not match this character "　", the ideographic space (U+3000), which was likely the character the patient had at the end of their name that Jerome removed. It's possible that the keyboard they used allowed the character, or they could have copy-pasted their name from elsewhere, which included the character.

Edit: I tested inputting the space as part of my name on registration and it caused a similar error on the backend, and put the invalid name into FHIR.

![image](https://github.com/umed-jp/umed/assets/67045972/60e6fe8a-1122-482a-aee4-2c8a6f4ed2f6)

Exception on /patients/ae272e84-1c49-4968-a583-efadcc1b926d [PATCH]
Error Log:
https://console.cloud.google.com/logs/query;cursorTimestamp=2024-04-11T07:05:35.914382Z;duration=PT1M;query=severity%3DERROR%0Atimestamp%3D%222024-04-11T07:05:35.914382Z%22%0AinsertId%3D%2266178bbf000df4ee2d6f8d99%22?project=kitsune-dev-313313

Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/app/src/utils/middleware.py", line 54, in wrapper
    return func(*args, **kwargs)
  File "/app/src/utils/middleware.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/app/src/blueprints/patients.py", line 52, in patch_patient
    return PatientController().patch_patient(request, patient_id)
  File "/app/src/blueprints/patients.py", line 246, in patch_patient
    patient = self.resource_client.patch_resource(patient_id, "Patient", patient)
  File "/app/src/adapters/fhir_store.py", line 289, in patch_resource
    return construct_fhir_element(resource_type, response.json())
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/fhir/resources/__init__.py", line 26, in construct_fhir_element
    return klass.parse_obj(data)
  File "pydantic/main.py", line 527, in pydantic.main.BaseModel.parse_obj
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/fhir/resources/fhirabstractmodel.py", line 138, in __init__
    BaseModel.__init__(__pydantic_self__, **data)
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Patient
name -> 0 -> given -> 0
  string does not match regex "[ \r\n\t\S]+" (type=value_error.str.regex; pattern=[ \r\n\t\S]+)

another one: 

![image](https://github.com/umed-jp/umed/assets/67045972/47d5bd72-8d81-4b6f-a2c0-ba05fb8cc0e5)

**Proposed actions:**

1. Add backwards compatibility, we can add some sanitation to the strings from fetched FHIR resources on the backend. However, since we haven't found any other occurrences, it might not be worth having it?

2. Add additional input validation on kitsune-frontend for the ideographic space, which FHIR doesn't accept as input.

**Comment by fauortiz** [comment]
3. add another input validation on backend as well.
