### ISSUE TITLE
:tada: Done:  appointment was not reflected in order

### ISSUE THREAD

**Issue by akirakakar** [umed-jp/umed#43]
Akira has posted an issue in Discord

https://practitioner-portal.web.app/appointments/80276ba2-9ba7-40a5-9682-b05342394c59

Appointment was not reflected in order

**Comment by rafael-parayno** [comment]
```
Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/notion_client/client.py", line 116, in _parse_response
    response.raise_for_status()
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/httpx/_models.py", line 749, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '409 Conflict' for url 'https://api.notion.com/v1/pages/4bbb9815-e415-4dce-b4e4-78f69d051ded'
For more information check: https://httpstatuses.com/409

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/app/src/blueprints/pubsub.py", line 29, in fhir
    return PubsubController().fhir(request)
  File "/app/src/blueprints/pubsub.py", line 105, in fhir
    return self._post_encounter(resource_id)
  File "/app/src/blueprints/pubsub.py", line 182, in _post_encounter
    self.notion_service.sync_encounter_to_notion(
  File "/app/src/services/notion_service.py", line 142, in sync_encounter_to_notion
    return self._client.pages.update(
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/notion_client/api_endpoints.py", line 218, in update
    return self.parent.request(
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/notion_client/client.py", line 192, in request
    return self._parse_response(response)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/notion_client/client.py", line 124, in _parse_response
    raise APIResponseError(response, body["message"], code)
notion_client.errors.APIResponseError: Conflict occurred while saving. Please try again.
```

**Comment by rafael-parayno** [comment]
this error causes by notion so thats why the firestore encounter didnt sync.

**Comment by tammytamayao** [comment]
Solution PR:
https://github.com/umed-jp/kitsune-backend/pull/444
