### ISSUE TITLE
🎉 Done: medication_requests POST issue oncall noise

### ISSUE THREAD

**Issue by rafael-parayno** [umed-jp/umed#84]
Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/app/src/utils/middleware.py", line 54, in wrapper
    return func(*args, **kwargs)
  File "/app/src/utils/middleware.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/app/src/blueprints/medication_requests.py", line 64, in create_medication_request
    return MedicationRequestController().create_medication_request()
  File "/app/src/blueprints/medication_requests.py", line 201, in create_medication_request
    ) = self.medication_request_service.create_medication_request(
  File "/app/src/services/medication_request_service.py", line 40, in create_medication_request
    fhir_dosage = self._map_to_fhir_dosage_instruction(medication)
  File "/app/src/services/medication_request_service.py", line 189, in _map_to_fhir_dosage_instruction
    Coding(code=usage_details["value"], display=usage_details["text"]),
TypeError: 'NoneType' object is not subscriptable

**Comment by rafael-parayno** [comment]
<img width="687" alt="image" src="https://github.com/umed-jp/umed/assets/52073048/058c59fa-99e0-4645-bde6-2236f95977c5">

**Comment by rafael-parayno** [comment]
https://github.com/umed-jp/kitsune-backend/pull/481
